name: Creative Design innovations
favicon: null
layout_spectrum: 0.10175
typography_spectrum: 0.56191
title: 'A Landscape Architecture and Land Planning firm in Huntsville, AL'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#a3c3a3'
    - '#ffffff'
    - '#808080'
    - '#000000'
    - '#80ff80'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
