name: Creative Design innovations
favicon: null
layout_spectrum: 0.93477
typography_spectrum: 0.85554
title: 'A Landscape Architecture and Land Planning firm in Huntsville, AL'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.2679539748933166
  lightness: 0.2653769471216947
  saturation: 0.6155051807872951
  rhythmicContrast: 0.42576270923018456
purpose: []
